language: node_js
node_js:
  - "node"

services:
  - docker

script:
  - docker build -t atroo/docker-ionic-fastlane-build:cordova-8 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push atroo/docker-ionic-fastlane-build:ionic3
